# Generated by Django 5.2.4 on 2025-07-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_instructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructions',
            new_name='Instruction',
        ),
    ]
